using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using KingmakerGunslinger.ElementalRaces;
namespace KingmakerGunslinger.DomainTests
{
    internal static class WhiteoutNativeFoundationTests
    {
        private static bool Environment(bool provider=true,bool map=true,bool indoor=false,WhiteoutPrecipitation weather=WhiteoutPrecipitation.Rain,int actual=1,bool module=true,bool contract=true,bool loaded=true)
        { return WhiteoutFoundationPolicy.EnvironmentActive(provider,map,indoor,weather,actual,module,contract,loaded); }
        private static string Mechanics { get { return File.ReadAllText("src/KingmakerGunslinger/ElementalRaces/WhiteoutNativeMechanics.cs"); } }
        private static string Fixture { get { return File.ReadAllText("src/KingmakerGunslinger/RuntimeTesting/RuntimeTestRunner.WhiteoutAttackFixture.cs"); } }
        internal static void ProviderAbsent() { Assertions.False(Environment(provider:false),"Exact provider required."); }
        internal static void RainLight() { Assertions.True(Environment(),"Outdoor native Rain Light qualifies."); }
        internal static void SnowLight() { Assertions.True(Environment(weather:WhiteoutPrecipitation.Snow),"Outdoor Snow Light qualifies."); }
        internal static void StrongerPrecipitation() { foreach(var w in new[]{WhiteoutPrecipitation.Rain,WhiteoutPrecipitation.Snow}) foreach(int i in new[]{2,3,4}) Assertions.True(Environment(weather:w,actual:i),"Native Moderate/Heavy/Storm qualify."); }
        internal static void IndoorRainSnow() { foreach(var w in new[]{WhiteoutPrecipitation.Rain,WhiteoutPrecipitation.Snow}) Assertions.False(Environment(indoor:true,weather:w),"Outdoors-only adaptation."); }
        internal static void ClearAndNormal() { Assertions.False(Environment(actual:0),"Visual Rain with actual Clear excluded."); Assertions.False(Environment(weather:WhiteoutPrecipitation.Normal,actual:4),"Normal excluded even with unrelated inclemency."); }
        internal static void UnknownMap() { Assertions.False(Environment(map:false),"Native missing-map false is not outdoor proof."); }
        internal static void ContractMismatch() { Assertions.False(Environment(contract:false),"Exact contract mismatch remains inactive."); }
        internal static void ModuleDisabled() { Assertions.False(Environment(module:false),"Module disabled stays inactive."); }
        internal static void MissingArea() { Assertions.False(Environment(loaded:false),"Unload/loading cannot grant active state."); }
        internal static void InvalidActualWeather() { foreach(int i in new[]{-1,5,100}) Assertions.False(Environment(actual:i),"Unknown native inclemency fails closed."); }
        internal static void RepeatedWeatherEvent() { var state=new WhiteoutWeatherState(); state.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true); for(int i=0;i<10;i++) state.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true); Assertions.Equal(1,state.TransitionCount,"Repeated native notifications are idempotent."); }
        internal static void ProviderRemoval() { var state=new WhiteoutWeatherState(); state.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true); state.OnMarkerRemoved(); Assertions.False(state.Active,"Removal clears."); Assertions.True(Mechanics.Contains("public override void OnTurnOff()") && Mechanics.Contains("public override void OnFactDeactivate()"),"Native fact/suppression/disposal lifecycles are wired."); }
        internal static void AreaUnload() { var state=new WhiteoutWeatherState(); state.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true); state.OnAreaUnloading(); Assertions.False(state.Active,"Unload clears."); Assertions.True(Mechanics.Contains("_areaUnloading=true") && Mechanics.Contains("bool area=!_areaUnloading"),"Attack-time refresh cannot reactivate unloading state."); }
        internal static void TwoOwnerStates() { var a=new WhiteoutWeatherState();var b=new WhiteoutWeatherState();a.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true);b.Reconcile(true,WhiteoutPrecipitation.Rain,1,false,true,true);a.OnMarkerRemoved();Assertions.False(a.Active,"First removed.");Assertions.True(b.Active,"Other owner unaffected."); }
        internal static void NativeFalseNoRoll() { int rolls=0; var d=new WhiteoutNativeStageDecision(); Assertions.False(d.AfterNative(false,true,()=>{rolls++;return 11;}),"Preserve native failure.");Assertions.Equal(0,rolls,"No Whiteout roll.");Assertions.False(d.Decided,"No native-failure replacement cache."); }
        internal static void InactiveNativeTrue() { int rolls=0;var d=new WhiteoutNativeStageDecision();Assertions.True(d.AfterNative(true,false,()=>{rolls++;return 1;}),"Inactive preserves native true.");Assertions.Equal(0,rolls,"No roll."); }
        internal static void Boundary1() { Boundary(1,false); }
        internal static void Boundary10() { Boundary(10,false); }
        internal static void Boundary11() { Boundary(11,true); }
        internal static void Boundary100() { Boundary(100,true); }
        private static void Boundary(int roll,bool expected) { var d=new WhiteoutNativeStageDecision();Assertions.Equal(expected,d.AfterNative(true,true,()=>roll),"Exact independent 10% boundary.");Assertions.Equal((int?)roll,d.Roll,"Exact observed d100 retained."); }
        internal static void ReplayOnce() { int rolls=0;var d=new WhiteoutNativeStageDecision();for(int i=0;i<10;i++) Assertions.False(d.AfterNative(true,true,()=>{rolls++;return 10;}),"Cached Whiteout miss.");Assertions.Equal(1,rolls,"Once per exact attack."); }
        internal static void NativeFalseAfterCachedSuccess() { var d=new WhiteoutNativeStageDecision();d.AfterNative(true,true,()=>11);Assertions.False(d.AfterNative(false,true,()=>11),"Cache never replaces later native concealment failure."); }
        internal static void NativeFalseAfterCachedMiss() { var d=new WhiteoutNativeStageDecision();d.AfterNative(true,true,()=>10);Assertions.False(d.AfterNative(false,true,()=>11),"Native false remains false independently."); }
        internal static void RemovalRevalidatesCachedMiss() { var d=new WhiteoutNativeStageDecision();d.AfterNative(true,true,()=>10);Assertions.True(d.AfterNative(true,false,()=>10),"Removed marker/weather/indoor change cannot apply stale cached protection."); }
        internal static void InactiveFirstDecisionNeverRerolls() { int count=0;var d=new WhiteoutNativeStageDecision();d.AfterNative(true,false,()=>10);Assertions.True(d.AfterNative(true,true,()=>{count++;return 10;}),"Replaying an initially inactive exact attack cannot create a new decision.");Assertions.Equal(0,count,"No replay roll."); }
        internal static void IgnoreConcealmentBypass() { Assertions.False(WhiteoutPolicy.ShouldRoll(true,true,true,true,false,true,true),"Native IgnoreConcealment bypass."); }
        internal static void ExactSeekingBypass() { Assertions.False(WhiteoutPolicy.ShouldRoll(true,true,true,false,true,true,true),"Exact authorized Seeking bypass.");Assertions.True(Mechanics.Contains("SeekingExactItemResolver.IsAuthorized(attack.Weapon)"),"Uses current exact project carrier resolver unchanged."); }
        internal static void ForeignSeekingNoBypass() { Assertions.True(WhiteoutPolicy.ShouldRoll(true,true,true,false,false,true,true),"Unauthorised lookalike has no bypass.");Assertions.True(Fixture.Contains("fake,canonical.AssetGuid") || (Fixture.Contains("SetValue(fake,canonical.AssetGuid)") && Fixture.Contains("!SeekingExactItemResolver.IsAuthorized(_lookalike)")),"Real fixture checks name/copied GUID/marker lookalike."); }
        internal static void IndependentAttackDecisions() { var a=new WhiteoutNativeStageDecision();var b=new WhiteoutNativeStageDecision();Assertions.False(a.AfterNative(true,true,()=>10),"First target attack misses.");Assertions.True(b.AfterNative(true,true,()=>11),"Second exact attack independent."); }
        internal static void ExceptionPreservesNative() { int count=0;var d=new WhiteoutNativeStageDecision();Assertions.True(d.AfterNative(true,true,()=>{count++;throw new InvalidOperationException();}),"Failure preserves native true.");Assertions.True(d.FailedOpen,"Error retained.");Assertions.True(d.AfterNative(true,true,()=>{count++;return 1;}),"Replay after failure cannot retry.");Assertions.Equal(1,count,"At most one RNG attempt, including error."); }
        internal static void InvalidRollFailsClosed() { var d=new WhiteoutNativeStageDecision();Assertions.True(d.AfterNative(true,true,()=>101),"Invalid diagnostic/native value preserves native result.");Assertions.True(d.FailedOpen,"Invalid d100 recorded as failure.");Assertions.Throws<ArgumentOutOfRangeException>(()=>WhiteoutPolicy.IsMiss(0),"Pure boundary rejects invalid value."); }
        internal static void ConcurrentReplayOnce() { int count=0;var d=new WhiteoutNativeStageDecision();Parallel.For(0,10,i=>Assertions.False(d.AfterNative(true,true,()=>{Interlocked.Increment(ref count);return 1;}),"One decision under concurrent exact-rule replay."));Assertions.Equal(1,count,"Atomic once-only roll."); }
        internal static void CombinedProbability28() { int miss=0;for(int native=1;native<=100;native++)for(int extra=1;extra<=100;extra++){var d=new WhiteoutNativeStageDecision();if(!d.AfterNative(native>20,true,()=>extra))miss++;}Assertions.Equal(2800,miss,"Native 20% plus independent 10% =28%, not30%."); }
        internal static void NarrowNativePatchAndCoverage() { string native=FieryGlareFoundationTests.Native("RuleAttackRoll::OnTrigger");Assertions.Equal(1,System.Text.RegularExpressions.Regex.Matches(native,"call[^\r\n]+RuleAttackRoll::TryOvercomeTargetConcealmentAndMissChance").Count,"One naturally shared native stage.");Assertions.True(Mechanics.Contains("method.GetMethodBody()?.GetILAsByteArray()?.Length!=149") && Mechanics.Contains("method.GetParameters().Length!=0") && Mechanics.Contains("NativeMvid"),"Pinned narrow exact contract, no broad rewrite.");foreach(string kind in new[]{"melee-10-miss","natural-10-miss","bow-10-miss","firearm-10-miss","ray-rangedtouch-10-miss"})Assertions.True(Fixture.Contains(kind),"Closed actual native matrix includes "+kind); }
        internal static void NonAttackPathsExcluded() { Assertions.False(Mechanics.Contains("RuleDealDamage") || Mechanics.Contains("RuleSavingThrow") || Mechanics.Contains("UnitPartConcealment.Max") || Mechanics.Contains("AttackRange ="),"No spell/save/damage/range/threat/concealment-tier patch."); }
        internal static void WeakExactAttackOwnership() { Assertions.True(Mechanics.Contains("ConditionalWeakTable<RuleAttackRoll,WhiteoutNativeStageDecision>") && !Mechanics.Contains("Dictionary<UnitEntityData"),"Weak exact rule key, no global owner dictionary."); }
        internal static void DiagnosticIsolation() { string d=File.ReadAllText("src/KingmakerGunslinger/RuntimeTesting/WhiteoutGuardedDiagnostics.cs");Assertions.True(d.Contains("[ThreadStatic]") && d.Contains("ReferenceEquals(scope._pending,attack)") && d.Contains("Thread.CurrentThread.ManagedThreadId==scope._thread") && d.Contains("ObserveUnpublishedWhiteoutFoundation") && d.Contains("return RulebookEvent.Dice.D100.Value") && d.Contains("WhiteoutAttackRuntime.Forget(attack)"),"Exact request/thread/attack; normal native d100; forced/cache state removed."); }
        internal static void NoPublication() { Assertions.False(File.ReadAllText("src/KingmakerGunslinger/Bootstrap/BlueprintBootstrap.cs").Contains("Whiteout"),"No bootstrap reachability.");Assertions.True(Mechanics.Contains("Guid.NewGuid()") && Mechanics.Contains("HiddenInUi") && !Mechanics.Contains("LocalizedString") && !Mechanics.Contains(".Register("),"Random unregistered hidden identity; no localization/icon/catalog/acquisition."); }
        internal static void NoPollingOrUnrelatedScan() { Assertions.False(Mechanics.Contains("void Update(") || Mechanics.Contains("State.Units.All") || Mechanics.Contains(".Tick()") || Mechanics.Contains("CurrentWeather =") || Mechanics.Contains("NextWeatherChange ="),"Production weather handler is event-driven/read-only and refreshes only the current target."); }
    }
}
