// Generated by tools/weapon_findability_native_reference.py from the verified 2.1.4 archive.
// Exact installed 2.1.7b comparisons are qualification evidence, not an assumption.
using System;
using System.Collections.Generic;
using System.Linq;
using Kingmaker.Blueprints.Loot;

namespace KingmakerGunslinger.Acquisition
{
    internal static class CampaignWeaponNativeReference
    {
        internal const string ArchiveSha256 = "6ddf33970fb9ed3c127dd8f30b6416d7d23f607303ca61a31aab1972ed43df60";
        private static readonly Dictionary<string, string> Expected = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "1f0bef6b8e540d644962171dc8810459", "436ec3989c26a3442ab12cb055b2b22f:1,f7d4d50f2978aab4db198b97304fbdc5:1,9065c71b61e1e064199a123e0e13348c:1,85880df1eadc4f343bfc3522a4d18f45:1" },
            { "77ad78d755a49af45abee46d86191b16", "ce5f776a6962b20469b6eaa3e2e584b1:1,a903724820fc3dc42aba0a6ad4436aaa:1,f2bc0997c24e573448c6c91d2be88afa:16" },
            { "c5adf784c614e4b4c8dc220111f64a54", "d2eb319bc6b399a48b1b1d0a73238ac4:1,c426180be627cf84284bc9abcada55af:1" },
            { "b54aad6aa2844fa4c87f46088cde018b", "4f68b70286eba114bb2f5fe5f18a566c:2,be452dba5acdd9441841d2189e1ae55a:1,0e0a31aaffda6464d9dd7fe97a14d267:4,c92308c160d6d424fb64f1fd708aa6cd:2,0c5f727578903c54e89e2c28a5f88d6d:3,f2bc0997c24e573448c6c91d2be88afa:1044" },
            { "e113fb75d9461924ab64df78c019991a", "6e37f3e99bfa1fb4a9ad8db1775aa7aa:3,4ab290cc7e961ff46a4d8744dea3f2c9:1,bdc4649575bff1b498cfb2471a8934da:1,c0989dca3e18c4c488b0b738b61bb924:2,47d41dd302a14d04faa7df70697d23ec:2,f2bc0997c24e573448c6c91d2be88afa:299" },
            { "5cce787544ae5964c8ac43ab7cf768ca", "9b64866b008a35d4ab1ba6f1a23bb7dc:1" },
            { "020246502ff864f4aab19e2fc00e63ee", "5b172c2c3e356eb43ba5a8f8008a8a5a:1,9a237496e6b3898498da4a2ecd9ed660:1,f2bc0997c24e573448c6c91d2be88afa:13" },
            { "e72cdc1e01c1eb144b6c29084dd111fb", "f20fef6a2bcfdf349afdbb26ae78463b:1,8b4d0b16bf3bced49a4e9c40e28ff756:1" },
            { "a2d14c56093720947a6ca4978c6a5985", "b3157283be1ddbc4abe94008acab5943:1,f991f3051c3b9e64fabc87891077b613:2,fac63f8aab736c5448ef775ee7250202:1" },
            { "4dc53495b10c62f4a90d4ae094d232c3", "4aea6773c1da01c42bd382c1b7c384bc:1" },
            { "2bffac36ed3499f4f9a1e6456e96a0f6", "47edb64bd292707448b2f6b207599a58:1" },
            { "df9ac89a7d8533a4e999bd267ae52b65", "aa726088e7616f34f8fa2aed8e12efe4:1" },
            { "d03682992a98a614c9d149fca2bab853", "f2bc0997c24e573448c6c91d2be88afa:121,240d326bb03e4cf4c9fb0bdded1dcff9:1" },
            { "2d95232e6fc0b594bb6e13e3d3ea0dc3", "4bfb51eb194395c4c8f7c13fdbce36e0:1,a3879b4e94c50854a873a0334fbbe36c:1,3f0351bb2f0608047acff46161f7a427:3,418a5f5ce964b5244bc7d2f1787bfe4f:3,fc7271d09ff1e9541935f1cc195682c4:1" },
            { "a9bb1f714425c564aadee3cc712fb96a", "12531e061aef4db40b337defa211512a:1,ee15329357f8f974bacf02521d8d37fe:1" },
            { "dd50c5c9d07eaaf49869308ce8720aec", "02e9f83be5d1c5d4e927b5c44ed34840:2,f28f6031c2908d84d945865a80f67177:3,c378f7531fffef049991b6f9740d6c05:1,19a5092244dcf99478dcd73c974828b1:1,f2bc0997c24e573448c6c91d2be88afa:189" },
            { "462bf0e4476e8c7498b2462219d46d25", "cf7071c32c435e2469ff921b87af6aea:2,31a74f20fcba2c9419738a94f6727dd6:1,ab1697d2523eb9142a145a773a635f36:1,f2bc0997c24e573448c6c91d2be88afa:71" },
            { "c0f1626bb1a0b3b47ad452ce75c7f0e2", "081a2ffe763320a469de20f1e9b1cd71:1" },
            { "732080f3aa72fd14cb520902e4b4db89", "17e5973a5ef49ce42ac49117d693efaa:2,17e5973a5ef49ce42ac49117d693efaa:2,d8d1c64ee071cb341a833dae24d35a10:1,511c97c1ea111444aa186b1a58496664:1,212a1a78c7865154482ffda45796510e:2,f2bc0997c24e573448c6c91d2be88afa:85" },
            { "3172f82c9f21b8a439a6552850b39b4c", "5bb722fed5172ed48baa2139246bc355:1,cf9694e0cab918d488dee655a08e4e1f:1,19a5092244dcf99478dcd73c974828b1:1,5a76d1b8138615644b214d42abd8b8fc:1,f2bc0997c24e573448c6c91d2be88afa:8,98f17a5556213024cae9663e4cf1164a:1" },
            { "b3344268950f27f4b840f216959f150e", "f0490c8af1fb22e46917359efc7bcf3d:1" },
            { "e3703cd9a6de2f24c80c1505e3c9784f", "6d7992679c557c842887c8bba08a12c8:1" },
            { "7e6448d1d8a7e4f4d9cc340b8f15e732", "5f6b606de240fcf4d941343e6c055179:1" },
            { "40db074f21260344b95d0e9919c8e682", "0a6a7bbf0ddcebb4f8c4c7bd5d20c003:1,2eda4fe6826aadc4f9b6fa91c7c773fd:1,f2bc0997c24e573448c6c91d2be88afa:10,3cfeae23012c8b9488b5b36d51ee4a8d:1" },
            { "3322c56f38031eb4983b6f87c95081b7", "1365aee7d18c85d438f5b027122ca8cf:2,de172db6e10f6d54896cb6a48b9fe8f7:3,f2bc0997c24e573448c6c91d2be88afa:43" },
            { "2aa7aa5c2df96b143bd2fc62a8547c9c", "b58b29d0dce442542859ed7599d38c28:1" },
            { "8a850f7758cb77b498621a307445bb1e", "f2bc0997c24e573448c6c91d2be88afa:940,88ec5262d0bb8f14f88ab97e3dd18915:1,abf90e9a19190b6428b2cb538b093cdd:1" },
            { "decb6060ab534294eb6d35510e45d317", "828561d73332c5846b11ffb4bd6df94d:1,2258062337f6ad9488bdd3b6e6b313b1:1,33674f7c73f0da0448ce6d84c6846f1a:1" },
            { "13e98ebc52714d34eb8e53f1099110fd", "11f435140501db84e8e787bf8792fac2:1,ba531e0a876d06c49aef207cc6c93056:1" },
        };
        internal static string Signature(IEnumerable<LootEntry> rows)
        {
            return string.Join(",", rows.Select(value => value == null ? "<null>" :
                (value.Item == null ? "<no-item>" : value.Item.AssetGuid) + ":" + value.Count).ToArray());
        }
        internal static string Require(string guid)
        {
            string value; if (!Expected.TryGetValue(guid, out value))
                throw new InvalidOperationException("No qualified native comparison contract for this target.");
            return value;
        }
    }
}
