[CmdletBinding()]
param([switch]$AllowMissing)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'common.ps1')
$root=Get-KmgRepositoryRoot -ScriptDirectory $PSScriptRoot
$directory=Join-Path $root 'assets\soundbanks'
$manifestPath=Join-Path $directory 'firearm-soundbank-manifest.json'
$bankPath=Join-Path $directory 'KMG_Firearms.bnk'
if(-not(Test-Path -LiteralPath $manifestPath -PathType Leaf) -or -not(Test-Path -LiteralPath $bankPath -PathType Leaf)){
  if($AllowMissing){Write-Host 'Source-only firearm SoundBank gate acknowledged: authentic bank/manifest absent.';return}
  throw 'Authentic KMG_Firearms.bnk and its production manifest are required for release packaging.'
}
$unexpected=@(Get-ChildItem -LiteralPath $directory -File | Where-Object {($_.Extension -in @('.bnk','.wem')) -and $_.Name -ne 'KMG_Firearms.bnk'})
if($unexpected){throw "Unexpected SoundBank/media artifact: $($unexpected.Name -join ', ')"}
if(Get-ChildItem -LiteralPath $directory -Recurse -File | Where-Object {$_.Name -ieq 'Init.bnk'}){throw 'Init.bnk is forbidden.'}
$manifest=Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
if($manifest.schemaVersion -ne 1 -or $manifest.bankName -ne 'KMG_Firearms' -or $manifest.bankFileName -ne 'KMG_Firearms.bnk' -or $manifest.platform -ne 'Windows' -or $manifest.mediaEmbedded -ne $true){throw 'Production firearm SoundBank manifest contract mismatch.'}
if($manifest.wwiseVersion -notmatch '^2016\.2\.'){throw 'Production bank must be generated by Wwise 2016.2.x.'}
if($manifest.sha256 -cnotmatch '^[0-9A-F]{64}$'){throw 'Production bank SHA-256 is invalid.'}
if((Get-KmgSha256 -Path $bankPath) -cne $manifest.sha256){throw 'Production firearm SoundBank hash mismatch.'}
$expected=@('KMG_Firearm_Pistol_Shot','KMG_Firearm_Musket_Shot','KMG_Firearm_Blunderbuss_Shot','KMG_Firearm_Revolver_Shot','KMG_Firearm_Rifle_Shot')
$actual=@($manifest.events.PSObject.Properties.Value)
if(($actual|Sort-Object)-join "`n" -cne ($expected|Sort-Object)-join "`n"){throw 'Production manifest event catalog mismatch.'}
Write-Host "Firearm SoundBank validation passed: $bankPath"
