#!/usr/bin/env python3
"""Compare complete production assignments with the explicitly supplied native dump.

This proves identities and ordered treasure rows only. It cannot prove scene
availability, an ordinary route, interaction, pickup or save persistence.
"""
import argparse
import hashlib
import json
import re
import zipfile
from pathlib import Path

ARCHIVE_SHA256 = '6ddf33970fb9ed3c127dd8f30b6416d7d23f607303ca61a31aab1972ed43df60'
ROOT = Path(__file__).resolve().parents[1]

def production_targets(root, read_source=None):
    specs = (
        ('RareFirearmCampaignLootBlueprints.cs', 'CleanupTargets', r'new TargetSpec\(MagicFirearmBlueprints\.(\w+),\s*"([^"]+)",\s*"([^"]+)",\s*"([^"]+)"'),
        ('EasternWeaponCampaignBlueprints.cs', 'CleanupLoot', r'new EasternLootSpec\("([^"]+)",\s*"([^"]+)",\s*"([^"]+)",\s*"[^"]+",\s*new\[\]\s*\{\s*EasternWeaponNamedKind\.(\w+)'),
        ('ElvenBranchedSpearCampaignBlueprints.cs', 'CleanupLoot', r'new LootSpec\(NamedSpearKind\.(\w+),\s*"([^"]+)",\s*"([^"]+)",\s*"([^"]+)"'),
    )
    result = []
    for file, end, pattern in specs:
        path = 'src/KingmakerGunslinger/Blueprints/'+file
        text = read_source(path) if read_source else (root/path).read_text(encoding='utf-8-sig')
        # Parse constructors only before the cleanup declaration; vendor specs
        # cannot match any of these three distinct signatures.
        active = text[:text.index('[] '+end)]
        for parts in re.findall(pattern, active):
            key, guid, name, area = (parts[3], *parts[:3]) if file.startswith('Eastern') else parts
            result.append(dict(key=key, family=file, targetGuid=guid, targetName=name, areaName=area))
    if len(result) != 29 or len({r['targetGuid'] for r in result}) != 29:
        raise AssertionError('Complete production registry must contain 29 distinct weapons and targets')
    return result

def compare(root, archive):
    if hashlib.sha256(archive.read_bytes()).hexdigest() != ARCHIVE_SHA256:
        raise AssertionError('Native comparison archive SHA-256 differs')
    with zipfile.ZipFile(archive) as z:
        by_guid = {n.rsplit('.',2)[-2]:n for n in z.namelist() if n.endswith('.json')}
        result=[]
        for target in production_targets(root):
            doc=json.loads(z.read(by_guid[target['targetGuid']]))
            _,area_guid,area_name=doc['Area'].split(':',2)
            if doc['name'] != target['targetName'] or area_name != target['areaName']:
                raise AssertionError('Exact native identity mismatch: '+repr(target))
            area=json.loads(z.read(by_guid[area_guid]))
            rows=[]
            for row in doc.get('Items',[]):
                _,guid,name=row['Item'].split(':',2)
                rows.append(dict(guid=guid,name=name,count=row['Count']))
            result.append({**target,'areaGuid':area_guid,'mapName':area.get('AreaName','').split(':',2)[-1],
                'mechanicsScene':area.get('m_DynamicScene',{}).get('m_SceneName'), 'nativeRows':rows,
                'sceneQualification':'UNVERIFIED','routeQualification':'UNVERIFIED',
                'pickupQualification':'UNVERIFIED','saveReloadQualification':'UNVERIFIED'})
        return dict(schemaVersion=1, comparisonGameVersion='2.1.4', archiveSha256=ARCHIVE_SHA256,
                    qualificationAuthority='installed 2.1.7b runtime; this file is reference data only',weapons=result)

def source(data):
    lines=['// Generated by tools/weapon_findability_native_reference.py from the verified 2.1.4 archive.',
           '// Exact installed 2.1.7b comparisons are qualification evidence, not an assumption.',
           'using System;', 'using System.Collections.Generic;', 'using System.Linq;',
           'using Kingmaker.Blueprints.Loot;', '', 'namespace KingmakerGunslinger.Acquisition', '{',
           '    internal static class CampaignWeaponNativeReference', '    {',
           '        internal const string ArchiveSha256 = "'+ARCHIVE_SHA256+'";',
           '        private static readonly Dictionary<string, string> Expected = new Dictionary<string, string>(StringComparer.Ordinal)',
           '        {']
    for r in data['weapons']:
        signature=','.join(row['guid']+':'+str(row['count']) for row in r['nativeRows'])
        lines.append('            { "'+r['targetGuid']+'", "'+signature+'" },')
    lines += ['        };', '        internal static string Signature(IEnumerable<LootEntry> rows)', '        {',
              '            return string.Join(",", rows.Select(value => value == null ? "<null>" :',
              '                (value.Item == null ? "<no-item>" : value.Item.AssetGuid) + ":" + value.Count).ToArray());',
              '        }', '        internal static string Require(string guid)', '        {',
              '            string value; if (!Expected.TryGetValue(guid, out value))',
              '                throw new InvalidOperationException("No qualified native comparison contract for this target.");',
              '            return value;', '        }', '    }', '}']
    return '\n'.join(lines)+'\n'

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--archive',type=Path,required=True)
    parser.add_argument('--write',action='store_true');args=parser.parse_args()
    data=compare(ROOT,args.archive)
    path=ROOT/'validation/weapon-findability-native-reference.json'
    cs=ROOT/'src/KingmakerGunslinger/Acquisition/CampaignWeaponNativeReference.cs'
    if args.write:
        path.write_text(json.dumps(data,indent=2)+'\n',encoding='utf-8')
        cs.write_text(source(data),encoding='utf-8')
    elif json.loads(path.read_text()) != data or cs.read_text() != source(data):
        raise AssertionError('Committed comparison contracts differ from exact archive and production tables')
    print('Native 2.1.4 reference comparison PASS: 29 exact targets; physical qualification UNVERIFIED')

if __name__=='__main__':main()
